/* eslint-disable */
/* Auto-generated by scripts/generate-sidebar.js — do not edit by hand */

import type { DefaultTheme } from 'vitepress'

export const sidebarMulti: DefaultTheme.SidebarMulti = {
  "/architecture/": [
    {
      text: "原子类型体系",
      link: "/architecture/atom-type-system"
    },
    {
      text: "架构图表集",
      link: "/architecture/diagrams"
    },
    {
      text: "MeTTa 程序执行流程",
      link: "/architecture/execution-flow"
    },
    {
      text: "模块系统",
      link: "/architecture/module-system"
    },
    {
      text: "整体架构",
      link: "/architecture/overview"
    },
    {
      text: "空间架构",
      link: "/architecture/space-architecture"
    }
  ],
  "/dev-guide/": [
    {
      text: "构建流程",
      link: "/dev-guide/build"
    },
    {
      text: "贡献指南",
      link: "/dev-guide/contributing"
    },
    {
      text: "环境搭建",
      link: "/dev-guide/setup"
    }
  ],
  "/experiments/": [
    {
      text: "Neurospace 实验",
      link: "/experiments/neurospace"
    },
    {
      text: "NumPy 实验（sandbox）",
      link: "/experiments/numpy"
    },
    {
      text: "其它实验目录",
      link: "/experiments/others"
    },
    {
      text: "PyTorch 实验（sandbox）",
      link: "/experiments/pytorch"
    },
    {
      text: "SQL Space 实验",
      link: "/experiments/sql-space"
    }
  ],
  "/extension-dev/": [
    {
      text: "自定义 Space 实现",
      link: "/extension-dev/custom-space"
    },
    {
      text: "Grounded 操作开发",
      link: "/extension-dev/grounded-ops"
    },
    {
      text: "模块打包与发布",
      link: "/extension-dev/module-packaging"
    },
    {
      text: "编写 Python 扩展",
      link: "/extension-dev/python-extension"
    }
  ],
  "/guide/": [
    {
      text: "第一个 MeTTa 程序",
      link: "/guide/first-metta-program"
    },
    {
      text: "安装指南",
      link: "/guide/installation"
    },
    {
      text: "Python API 快速入门",
      link: "/guide/python-quickstart"
    }
  ],
  "/metta-lang/": [
    {
      text: "Semantics",
      collapsed: true,
      items: [
      {
        text: "MeTTa 基础语法：从文本到 Atom 的全链分析",
        link: "/metta-lang/semantics/01-basic-syntax"
      },
      {
        text: "MeTTa 函数与等式：Space、`eval`、查询与合一",
        link: "/metta-lang/semantics/02-functions-equations"
      },
      {
        text: "MeTTa 类型系统：`(:` / `(:<` / `->` / `%Undefined%` / `pragma!`",
        link: "/metta-lang/semantics/03-type-system"
      },
      {
        text: "最小指令集：全链路实现",
        link: "/metta-lang/semantics/04-minimal-instructions"
      },
      {
        text: "模式匹配与查询：全链路实现",
        link: "/metta-lang/semantics/05-pattern-matching"
      },
      {
        text: "非确定性计算：全链路实现",
        link: "/metta-lang/semantics/06-nondeterminism"
      },
      {
        text: "文档 7：控制流（MeTTa → 解释器 Rust → Python/C 边界）",
        link: "/metta-lang/semantics/07-control-flow"
      },
      {
        text: "文档 8：空间操作（MeTTa → Rust 算子 → GroundingSpace → Python/C）",
        link: "/metta-lang/semantics/08-space-operations"
      },
      {
        text: "文档 9：状态管理（`new-state` / `get-state` / `change-state!` / `bind!`）",
        link: "/metta-lang/semantics/09-state-management"
      },
      {
        text: "文档 10：算术与逻辑运算全链实现",
        link: "/metta-lang/semantics/10-arithmetic-logic"
      },
      {
        text: "文档 11：数学函数全链实现",
        link: "/metta-lang/semantics/11-math-functions"
      },
      {
        text: "文档 12：字符串操作全链实现",
        link: "/metta-lang/semantics/12-string-operations"
      },
      {
        text: "文档 13：原子操作（MeTTa → Python → Rust）",
        link: "/metta-lang/semantics/13-atom-operations"
      },
      {
        text: "文档 14：模块系统（MeTTa → Python → Rust）",
        link: "/metta-lang/semantics/14-module-system"
      },
      {
        text: "文档 15：文档系统（@doc / help! / help-space!）",
        link: "/metta-lang/semantics/15-documentation-system"
      },
      {
        text: "文档 16：调试与测试（MeTTa → Python → Rust）",
        link: "/metta-lang/semantics/16-debug-testing"
      },
      {
        text: "文档 17：包管理（MeTTa → Python → Rust）",
        link: "/metta-lang/semantics/17-package-management"
      },
      {
        text: "文档 18：Python 互操作（MeTTa → Python → Rust / C++）",
        link: "/metta-lang/semantics/18-python-interop"
      }
      ]
    },
    {
      text: "Tutorial",
      collapsed: true,
      items: [
      {
        text: "a1_symbols.metta",
        link: "/metta-lang/tutorial/a1-symbols"
      },
      {
        text: "a2_opencoggy.metta",
        link: "/metta-lang/tutorial/a2-opencoggy"
      },
      {
        text: "a3_twoside.metta",
        link: "/metta-lang/tutorial/a3-twoside"
      },
      {
        text: "b0_chaining_prelim.metta",
        link: "/metta-lang/tutorial/b0-chaining-prelim"
      },
      {
        text: "b1_equal_chain.metta",
        link: "/metta-lang/tutorial/b1-equal-chain"
      },
      {
        text: "b2_backchain.metta",
        link: "/metta-lang/tutorial/b2-backchain"
      },
      {
        text: "b3_direct.metta",
        link: "/metta-lang/tutorial/b3-direct"
      },
      {
        text: "b4_nondeterm.metta",
        link: "/metta-lang/tutorial/b4-nondeterm"
      },
      {
        text: "b5_types_prelim.metta",
        link: "/metta-lang/tutorial/b5-types-prelim"
      },
      {
        text: "c1_grounded_basic.metta",
        link: "/metta-lang/tutorial/c1-grounded-basic"
      },
      {
        text: "c2_spaces_kb.metta",
        link: "/metta-lang/tutorial/c2-spaces-kb"
      },
      {
        text: "c2_spaces.metta",
        link: "/metta-lang/tutorial/c2-spaces"
      },
      {
        text: "c3_pln_stv.metta",
        link: "/metta-lang/tutorial/c3-pln-stv"
      },
      {
        text: "d1_gadt.metta",
        link: "/metta-lang/tutorial/d1-gadt"
      },
      {
        text: "d2_higherfunc.metta",
        link: "/metta-lang/tutorial/d2-higherfunc"
      },
      {
        text: "d3_deptypes.metta",
        link: "/metta-lang/tutorial/d3-deptypes"
      },
      {
        text: "d4_type_prop.metta",
        link: "/metta-lang/tutorial/d4-type-prop"
      },
      {
        text: "d5_auto_types.metta",
        link: "/metta-lang/tutorial/d5-auto-types"
      },
      {
        text: "e1_kb_write.metta",
        link: "/metta-lang/tutorial/e1-kb-write"
      },
      {
        text: "e2_states.metta",
        link: "/metta-lang/tutorial/e2-states"
      },
      {
        text: "e3_match_states.metta",
        link: "/metta-lang/tutorial/e3-match-states"
      },
      {
        text: "f1_imports.metta",
        link: "/metta-lang/tutorial/f1-imports"
      },
      {
        text: "g1_docs.metta",
        link: "/metta-lang/tutorial/g1-docs"
      }
      ]
    },
    {
      text: "非确定性求值专题",
      link: "/metta-lang/nondeterminism"
    },
    {
      text: "MeTTa 语言概述",
      link: "/metta-lang/overview"
    },
    {
      text: "MeTTa 语言规范（精简版）",
      link: "/metta-lang/specification"
    },
    {
      text: "标准库完整参考（Core + stdlib.metta）",
      link: "/metta-lang/stdlib-reference"
    }
  ],
  "/python-api/": [
    {
      text: "模块 `hyperon.atoms` — 公共 API",
      link: "/python-api/atoms"
    },
    {
      text: "模块 `hyperon.base` — 公共 API",
      link: "/python-api/base"
    },
    {
      text: "模块 `hyperon.conversion` — 公共 API",
      link: "/python-api/conversion"
    },
    {
      text: "模块 `hyperon.ext` — 公共 API",
      link: "/python-api/ext"
    },
    {
      text: "模块 `hyperon.module` — 公共 API",
      link: "/python-api/module"
    },
    {
      text: "模块 `hyperon.runner` — 公共 API",
      link: "/python-api/runner"
    },
    {
      text: "模块 `hyperon.stdlib` — 公共 API",
      link: "/python-api/stdlib"
    }
  ],
  "/python-source/": [
    {
      text: "agents：agent.metta",
      link: "/python-source/agents-agent-metta"
    },
    {
      text: "`agents/agent_base.py` 分析报告",
      link: "/python-source/agents-base"
    },
    {
      text: "`agents/events/basic_bus.py` 分析报告",
      link: "/python-source/agents-events-bus"
    },
    {
      text: "`agents/events/__init__.py` 分析报告",
      link: "/python-source/agents-events-init"
    },
    {
      text: "`agents/__init__.py` 分析报告",
      link: "/python-source/agents-init"
    },
    {
      text: "agents：test_0_passive_agents.metta",
      link: "/python-source/agents-test-0-passive-agents"
    },
    {
      text: "agents：test_4_agent1.metta",
      link: "/python-source/agents-test-4-agent1"
    },
    {
      text: "agents：test_4_agent2.metta",
      link: "/python-source/agents-test-4-agent2"
    },
    {
      text: "agents：test_4_events.metta",
      link: "/python-source/agents-test-4-events"
    },
    {
      text: "`agents/tests/test_1_python_agents.py` 分析报告",
      link: "/python-source/agents-test1"
    },
    {
      text: "`agents/tests/test_2_daemon.py` 分析报告",
      link: "/python-source/agents-test2"
    },
    {
      text: "`agents/tests/test_3_events_python.py` 分析报告",
      link: "/python-source/agents-test3"
    },
    {
      text: "`python/hyperon/atoms.py` Python 源码分析报告",
      link: "/python-source/atoms"
    },
    {
      text: "`python/hyperon/base.py` Python 源码分析报告",
      link: "/python-source/base"
    },
    {
      text: "`lib/src/metta/runner/builtin_mods/catalog.metta` MeTTa 源码分析报告",
      link: "/python-source/builtin-catalog-metta"
    },
    {
      text: "`lib/src/metta/runner/builtin_mods/das.metta` MeTTa 源码分析报告",
      link: "/python-source/builtin-das-metta"
    },
    {
      text: "`lib/src/metta/runner/builtin_mods/fileio.metta` MeTTa 源码分析报告",
      link: "/python-source/builtin-fileio-metta"
    },
    {
      text: "`lib/src/metta/runner/builtin_mods/json.metta` MeTTa 源码分析报告",
      link: "/python-source/builtin-json-metta"
    },
    {
      text: "`lib/src/metta/runner/builtin_mods/random.metta` MeTTa 源码分析报告",
      link: "/python-source/builtin-random-metta"
    },
    {
      text: "`lib/src/metta/runner/builtin_mods/skel.metta` MeTTa 源码分析报告",
      link: "/python-source/builtin-skel-metta"
    },
    {
      text: "c/conanfile.py",
      link: "/python-source/conanfile-c"
    },
    {
      text: "python/conanfile.py",
      link: "/python-source/conanfile-py"
    },
    {
      text: "`python/hyperon/conversion.py` Python 源码分析报告",
      link: "/python-source/conversion"
    },
    {
      text: "debug_metta.py（仓库根）",
      link: "/python-source/debug-metta"
    },
    {
      text: "`lib/src/metta/runner/environment.default.metta` MeTTa 源码分析报告",
      link: "/python-source/env-default-metta"
    },
    {
      text: "ext_dir/ext.py 分析报告",
      link: "/python-source/ext-dir-ext"
    },
    {
      text: "ext_dir/__init__.py 分析报告",
      link: "/python-source/ext-dir-init"
    },
    {
      text: "ext_recursive/level-2/ext_nested/ext.py 分析报告",
      link: "/python-source/ext-recursive-ext"
    },
    {
      text: "ext_recursive/level-2/ext_nested/__init__.py 分析报告",
      link: "/python-source/ext-recursive-init"
    },
    {
      text: "ext_sub/ext_nested/ext.py 分析报告",
      link: "/python-source/ext-sub-ext"
    },
    {
      text: "ext_sub/ext_nested/__init__.py 分析报告",
      link: "/python-source/ext-sub-init"
    },
    {
      text: "ext_sub/module.metta",
      link: "/python-source/ext-sub-module-metta"
    },
    {
      text: "`python/hyperon/ext.py` Python 源码分析报告",
      link: "/python-source/ext"
    },
    {
      text: "f1_moduleA.metta",
      link: "/python-source/f1-moduleA"
    },
    {
      text: "f1_moduleB.metta",
      link: "/python-source/f1-moduleB"
    },
    {
      text: "f1_moduleC.metta",
      link: "/python-source/f1-moduleC"
    },
    {
      text: "`lib/src/metta/runner/init.default.metta` MeTTa 源码分析报告",
      link: "/python-source/init-default-metta"
    },
    {
      text: "`python/hyperon/__init__.py` Python 源码分析报告",
      link: "/python-source/init"
    },
    {
      text: "`python/hyperon/metta.py` Python 源码分析报告",
      link: "/python-source/metta-cli"
    },
    {
      text: "metta_examples.py（仓库根）",
      link: "/python-source/metta-examples"
    },
    {
      text: "`python/hyperon/module.py` Python 源码分析报告",
      link: "/python-source/module"
    },
    {
      text: "other：animals.metta（DAS）",
      link: "/python-source/other-das-animals"
    },
    {
      text: "other：test.metta（DAS）",
      link: "/python-source/other-das-test"
    },
    {
      text: "other：mkdocs.metta",
      link: "/python-source/other-mkdocs"
    },
    {
      text: "other：test_gnd_conv.metta",
      link: "/python-source/other-test-gnd-conv"
    },
    {
      text: "`py_ops/__init__.py` 分析报告",
      link: "/python-source/py-ops-init"
    },
    {
      text: "`py_ops/pyop.py` 分析报告",
      link: "/python-source/py-ops-pyop"
    },
    {
      text: "repl/src/py_shim.py",
      link: "/python-source/py-shim"
    },
    {
      text: "repl.default.metta",
      link: "/python-source/repl-default-metta"
    },
    {
      text: "`python/hyperon/runner.py` Python 源码分析报告",
      link: "/python-source/runner"
    },
    {
      text: "sandbox：bhv 01 多数绑定",
      link: "/python-source/sandbox-bhv-01-majority"
    },
    {
      text: "sandbox：bhv 02 置换",
      link: "/python-source/sandbox-bhv-02-perm"
    },
    {
      text: "sandbox：bhv 03 字典",
      link: "/python-source/sandbox-bhv-03-dict"
    },
    {
      text: "sandbox：bhv 04 墨西哥美元",
      link: "/python-source/sandbox-bhv-04-mexico"
    },
    {
      text: "bhv_binding.py（沙箱）",
      link: "/python-source/sandbox-bhv"
    },
    {
      text: "sandbox：jetta 枚举 λ",
      link: "/python-source/sandbox-jetta-enum-lambda"
    },
    {
      text: "sandbox：jetta 基础",
      link: "/python-source/sandbox-jetta-test-basic"
    },
    {
      text: "sandbox：jetta compile 表达式",
      link: "/python-source/sandbox-jetta-test-expr-compile"
    },
    {
      text: "sandbox：jetta λ",
      link: "/python-source/sandbox-jetta-test-lambda"
    },
    {
      text: "sandbox：jetta 非确定性",
      link: "/python-source/sandbox-jetta-test-nondet"
    },
    {
      text: "compile.py（Jetta 沙箱）",
      link: "/python-source/sandbox-jetta"
    },
    {
      text: "kwargsme.py（沙箱）",
      link: "/python-source/sandbox-kwargsme"
    },
    {
      text: "sandbox：mork",
      link: "/python-source/sandbox-mork-test-mork"
    },
    {
      text: "mork.py（沙箱）",
      link: "/python-source/sandbox-mork"
    },
    {
      text: "sandbox：neurospace",
      link: "/python-source/sandbox-neurospace-test-nspace"
    },
    {
      text: "neurospace.py（沙箱）",
      link: "/python-source/sandbox-neurospace"
    },
    {
      text: "numme.py（沙箱）",
      link: "/python-source/sandbox-numme"
    },
    {
      text: "sandbox：numme",
      link: "/python-source/sandbox-numpy-nm-test"
    },
    {
      text: "parsing_exceptions.py（沙箱）",
      link: "/python-source/sandbox-parsing-exc"
    },
    {
      text: "sandbox：torchme",
      link: "/python-source/sandbox-pytorch-tm-test"
    },
    {
      text: "r.py（沙箱）",
      link: "/python-source/sandbox-r"
    },
    {
      text: "metta_repl.py（沙箱）",
      link: "/python-source/sandbox-repl"
    },
    {
      text: "sandbox：resolve",
      link: "/python-source/sandbox-resolve-r"
    },
    {
      text: "resolve.py（沙箱）",
      link: "/python-source/sandbox-resolve"
    },
    {
      text: "sandbox：sql_space",
      link: "/python-source/sandbox-sql-space-test"
    },
    {
      text: "sql_space.py（沙箱）",
      link: "/python-source/sandbox-sql"
    },
    {
      text: "tm_test.py（沙箱）",
      link: "/python-source/sandbox-tmtest"
    },
    {
      text: "parse_torch_func_signatures.py（沙箱）",
      link: "/python-source/sandbox-torch-sig"
    },
    {
      text: "torchme.py（沙箱）",
      link: "/python-source/sandbox-torchme"
    },
    {
      text: "`python/setup.py` Python 源码分析报告",
      link: "/python-source/setup"
    },
    {
      text: "`snet_io/snet_gate.py` 分析报告",
      link: "/python-source/snet-gate"
    },
    {
      text: "`snet_io/__init__.py` 分析报告",
      link: "/python-source/snet-init"
    },
    {
      text: "snet_io：text-generation.metta",
      link: "/python-source/snet-naint-text-generation"
    },
    {
      text: "snet_io：test_snet_call.metta",
      link: "/python-source/snet-test-snet-call"
    },
    {
      text: "snet_io：test_snet_meta.metta",
      link: "/python-source/snet-test-snet-meta"
    },
    {
      text: "`lib/src/metta/runner/stdlib/stdlib.metta` MeTTa 源码分析报告",
      link: "/python-source/stdlib-metta"
    },
    {
      text: "`python/hyperon/stdlib.py` Python 源码分析报告",
      link: "/python-source/stdlib"
    },
    {
      text: "test_atom_type.py 分析报告",
      link: "/python-source/test-atom-type"
    },
    {
      text: "test_atom.py 分析报告",
      link: "/python-source/test-atom"
    },
    {
      text: "test_bindings.py 分析报告",
      link: "/python-source/test-bindings"
    },
    {
      text: "test_common.py 分析报告",
      link: "/python-source/test-common"
    },
    {
      text: "test_custom_space.py 分析报告",
      link: "/python-source/test-custom-space"
    },
    {
      text: "test_environment.py 分析报告",
      link: "/python-source/test-environment"
    },
    {
      text: "error_pyext.py 分析报告",
      link: "/python-source/test-error-pyext"
    },
    {
      text: "test_examples.py 分析报告",
      link: "/python-source/test-examples"
    },
    {
      text: "test_extend.py 分析报告",
      link: "/python-source/test-extend"
    },
    {
      text: "extension.py 分析报告",
      link: "/python-source/test-extension"
    },
    {
      text: "test_grounded_type.py 分析报告",
      link: "/python-source/test-grounded-type"
    },
    {
      text: "test_grounding_space.py 分析报告",
      link: "/python-source/test-grounding-space"
    },
    {
      text: "test_include.metta",
      link: "/python-source/test-include-metta"
    },
    {
      text: "test_load.metta",
      link: "/python-source/test-load-metta"
    },
    {
      text: "test_load.py 分析报告",
      link: "/python-source/test-load"
    },
    {
      text: "test_metta.py 分析报告",
      link: "/python-source/test-metta"
    },
    {
      text: "test_modules.py 分析报告",
      link: "/python-source/test-modules"
    },
    {
      text: "test_pln_tv.py 分析报告",
      link: "/python-source/test-pln-tv"
    },
    {
      text: "pyfile_test_mod.py 分析报告",
      link: "/python-source/test-pyfile-test-mod"
    },
    {
      text: "test_run_metta.py 分析报告",
      link: "/python-source/test-run-metta"
    },
    {
      text: "test_sexparser.py 分析报告",
      link: "/python-source/test-sexparser"
    },
    {
      text: "`lib/tests/test_stdlib.metta` MeTTa 源码分析报告",
      link: "/python-source/test-stdlib-metta"
    },
    {
      text: "test_stdlib.py 分析报告",
      link: "/python-source/test-stdlib"
    },
    {
      text: "python/integration/test_torch.py",
      link: "/python-source/test-torch"
    }
  ],
  "/rust-engine/": [
    {
      text: "C Api",
      collapsed: true,
      items: [
      {
        text: "`c/src/lib.rs` 分析报告",
        link: "/rust-engine/c-api/lib"
      },
      {
        text: "`c/src/module.rs` 分析报告",
        link: "/rust-engine/c-api/module"
      },
      {
        text: "`c/src/util.rs` 分析报告",
        link: "/rust-engine/c-api/util"
      }
      ]
    },
    {
      text: "Hyperon Atom",
      collapsed: true,
      items: [
      {
        text: "`hyperon-atom/src/lib.rs` 源码分析报告：Atom ADT 与 Grounded 体系",
        link: "/rust-engine/hyperon-atom/atom-adt"
      },
      {
        text: "`gnd/bool.rs` 源码分析：Bool",
        link: "/rust-engine/hyperon-atom/gnd-bool"
      },
      {
        text: "`gnd/mod.rs` 源码分析：GroundedFunction 包装与 grounded 相等性",
        link: "/rust-engine/hyperon-atom/gnd-mod"
      },
      {
        text: "`gnd/str.rs` 源码分析：Str 与字符串工具",
        link: "/rust-engine/hyperon-atom/gnd-str"
      },
      {
        text: "`iter.rs` 源码分析",
        link: "/rust-engine/hyperon-atom/iter"
      },
      {
        text: "`tests/macros.rs` 源码分析：`metta!` 宏集成测试",
        link: "/rust-engine/hyperon-atom/macros-test"
      },
      {
        text: "`hyperon-atom/src/matcher.rs` 源码分析报告",
        link: "/rust-engine/hyperon-atom/matcher"
      },
      {
        text: "`serial.rs` 源码分析",
        link: "/rust-engine/hyperon-atom/serial"
      },
      {
        text: "`subexpr.rs` 源码分析",
        link: "/rust-engine/hyperon-atom/subexpr"
      }
      ]
    },
    {
      text: "Hyperon Common",
      collapsed: true,
      items: [
      {
        text: "assert 模块源码分析",
        link: "/rust-engine/hyperon-common/assert"
      },
      {
        text: "`hyperon-common/src/collections.rs` 源码分析",
        link: "/rust-engine/hyperon-common/collections"
      },
      {
        text: "灵活引用（FlexRef）",
        link: "/rust-engine/hyperon-common/flex-ref"
      },
      {
        text: "HoleyVec 源码分析（`holeyvec.rs`）",
        link: "/rust-engine/hyperon-common/holeyvec"
      },
      {
        text: "不可变字符串（ImmutableString）",
        link: "/rust-engine/hyperon-common/immutable-string"
      },
      {
        text: "`multitrie.rs` 源码分析（重点：AtomIndex 依赖的多值 Trie）",
        link: "/rust-engine/hyperon-common/multitrie"
      },
      {
        text: "hyperon-common/src/lib.rs 源码分析",
        link: "/rust-engine/hyperon-common/overview"
      },
      {
        text: "OwnedOrBorrowed 源码分析",
        link: "/rust-engine/hyperon-common/owned-or-borrowed"
      },
      {
        text: "RefOrMove：按值或按引用统一访问",
        link: "/rust-engine/hyperon-common/reformove"
      },
      {
        text: "`shared.rs` 源码分析",
        link: "/rust-engine/hyperon-common/shared"
      }
      ]
    },
    {
      text: "Hyperon Space",
      collapsed: true,
      items: [
      {
        text: "`index/mod.rs` 源码分析：AtomIndex 与基于 Trie 的索引门面",
        link: "/rust-engine/hyperon-space/atom-index"
      },
      {
        text: "`index/storage.rs` 源码分析：AtomStorage 双映射",
        link: "/rust-engine/hyperon-space/atom-storage"
      },
      {
        text: "`index/trie.rs` 源码分析：AtomTrie、Trie 节点与 DuplicationStrategy",
        link: "/rust-engine/hyperon-space/atom-trie"
      },
      {
        text: "`benches/atom_index.rs` 源码分析：AtomIndex 基准",
        link: "/rust-engine/hyperon-space/bench"
      },
      {
        text: "`lib.rs` 源码分析：Space 特质体系、DynSpace 与观察者",
        link: "/rust-engine/hyperon-space/space-traits"
      }
      ]
    },
    {
      text: "Interpreter",
      collapsed: true,
      items: [
      {
        text: "`lib/src/metta/interpreter.rs` 源码分析报告（最小 MeTTa 解释器核心）",
        link: "/rust-engine/interpreter/interpreter"
      },
      {
        text: "`lib/src/metta/mod.rs` 源码分析报告",
        link: "/rust-engine/interpreter/metta-mod"
      }
      ]
    },
    {
      text: "Modules",
      collapsed: true,
      items: [
      {
        text: "`lib/src/metta/runner/modules/mod.rs` 源码分析报告（MettaMod 与 ModuleLoader）",
        link: "/rust-engine/modules/metta-mod"
      },
      {
        text: "`lib/src/metta/runner/modules/mod_names.rs` 源码分析报告（模块名路径与名称树）",
        link: "/rust-engine/modules/mod-name-tree"
      }
      ]
    },
    {
      text: "Parser",
      collapsed: true,
      items: [
      {
        text: "`lib/src/metta/text.rs` 源码分析报告",
        link: "/rust-engine/parser/text"
      }
      ]
    },
    {
      text: "Runner",
      collapsed: true,
      items: [
      {
        text: "`lib/src/metta/runner/mod.rs` 源码分析报告（MeTTa Runner 核心）",
        link: "/rust-engine/runner/metta-struct"
      }
      ]
    },
    {
      text: "Stdlib Rust",
      collapsed: true,
      items: [
      {
        text: "`stdlib/arithmetics.rs` — 算术、比较与布尔接地运算",
        link: "/rust-engine/stdlib-rust/arithmetics"
      },
      {
        text: "`stdlib/atom.rs` — 原子列表、类型与元类型运算",
        link: "/rust-engine/stdlib-rust/atom-ops"
      },
      {
        text: "`stdlib/core.rs` — 核心控制与原语级运算",
        link: "/rust-engine/stdlib-rust/core"
      },
      {
        text: "`stdlib/math.rs` — 数学库函数与常量",
        link: "/rust-engine/stdlib-rust/math"
      },
      {
        text: "`stdlib/package.rs` — 包管理：本地路径与 Git 模块",
        link: "/rust-engine/stdlib-rust/package"
      },
      {
        text: "`stdlib/space.rs` — 空间与 StateMonad",
        link: "/rust-engine/stdlib-rust/space-state"
      }
      ]
    },
    {
      text: "Type System",
      collapsed: true,
      items: [
      {
        text: "`lib/src/metta/types.rs` 源码分析报告",
        link: "/rust-engine/type-system/types"
      }
      ]
    },
    {
      text: "`lib/benches/grounding_space.rs` 分析报告",
      link: "/rust-engine/bench-grounding"
    },
    {
      text: "`lib/benches/interpreter_minimal.rs` 分析报告",
      link: "/rust-engine/bench-interpreter"
    },
    {
      text: "`lib/benches/states.rs` 分析报告",
      link: "/rust-engine/bench-states"
    },
    {
      text: "`lib/benches/type.rs` 分析报告",
      link: "/rust-engine/bench-type"
    },
    {
      text: "内置模块：`builtin_mods/catalog.rs`",
      link: "/rust-engine/builtin-catalog"
    },
    {
      text: "内置模块：`builtin_mods/fileio.rs`",
      link: "/rust-engine/builtin-fileio"
    },
    {
      text: "内置模块：`builtin_mods/json.rs`",
      link: "/rust-engine/builtin-json"
    },
    {
      text: "内置模块入口：`builtin_mods/mod.rs`",
      link: "/rust-engine/builtin-mods-entry"
    },
    {
      text: "内置模块：`builtin_mods/random.rs`",
      link: "/rust-engine/builtin-random"
    },
    {
      text: "`lib/examples/custom_match.rs` 分析报告",
      link: "/rust-engine/example-custom-match"
    },
    {
      text: "`lib/examples/load_space.rs` 分析报告",
      link: "/rust-engine/example-load-space"
    },
    {
      text: "`lib/examples/sorted_list.rs` 分析报告",
      link: "/rust-engine/example-sorted-list"
    },
    {
      text: "`lib/src/space/grounding/mod.rs` 源码分析报告",
      link: "/rust-engine/grounding-space"
    },
    {
      text: "`hyperon-macros/src/lib.rs` 源码分析报告",
      link: "/rust-engine/hyperon-macros"
    },
    {
      text: "`lib/src/lib.rs` 源码分析报告",
      link: "/rust-engine/lib-entry"
    },
    {
      text: "`lib/src/space/module.rs` 源码分析报告",
      link: "/rust-engine/module-space"
    },
    {
      text: "包管理：`pkg_mgmt/catalog.rs`",
      link: "/rust-engine/pkg-mgmt-catalog"
    },
    {
      text: "包管理：`pkg_mgmt/managed_catalog.rs`",
      link: "/rust-engine/pkg-mgmt-managed"
    },
    {
      text: "包管理子系统入口：`pkg_mgmt/mod.rs`",
      link: "/rust-engine/pkg-mgmt-mod"
    },
    {
      text: "`repl/src/config_params.rs` 分析报告",
      link: "/rust-engine/repl-config"
    },
    {
      text: "`repl/src/interactive_helper.rs` 分析报告",
      link: "/rust-engine/repl-helper"
    },
    {
      text: "`repl/src/main.rs` 分析报告",
      link: "/rust-engine/repl-main"
    },
    {
      text: "`repl/src/metta_shim.rs` 分析报告",
      link: "/rust-engine/repl-shim"
    },
    {
      text: "`lib/src/space/mod.rs` 源码分析报告",
      link: "/rust-engine/space-mod"
    },
    {
      text: "`lib/tests/case.rs` 分析报告",
      link: "/rust-engine/test-case"
    },
    {
      text: "`lib/tests/metta.rs` 分析报告",
      link: "/rust-engine/test-metta"
    },
    {
      text: "`lib/tests/space.rs` 分析报告",
      link: "/rust-engine/test-space"
    },
    {
      text: "`lib/tests/types.rs` 分析报告",
      link: "/rust-engine/test-types"
    },
    {
      text: "Rust Workspace 总览与 Crate 依赖",
      link: "/rust-engine/workspace-overview"
    }
  ],
  "/testing/": [
    {
      text: "测试架构",
      link: "/testing/architecture"
    },
    {
      text: "MeTTa 脚本测试说明",
      link: "/testing/metta-tests"
    },
    {
      text: "Python 测试说明",
      link: "/testing/python-tests"
    }
  ],
  "/theory/": [
    {
      text: "AGI 与认知架构（OpenCog Hyperon 视角）",
      link: "/theory/agi-cognitive"
    },
    {
      text: "知识表示与超图（Hyperon / MeTTa）",
      link: "/theory/knowledge-representation"
    },
    {
      text: "元编程与自引导（MeTTa / Hyperon）",
      link: "/theory/metaprogramming"
    },
    {
      text: "模式匹配与合一（Unification）",
      link: "/theory/pattern-matching-unification"
    },
    {
      text: "推理方法（前向链、后向链、PLN）",
      link: "/theory/reasoning"
    },
    {
      text: "类型论与 MeTTa",
      link: "/theory/type-theory"
    }
  ]
}
